name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Add HTTP package here (NOT inside flutter)
  http: ^1.1.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/1.jpg
    - lib/images/2.jpg
    - lib/images/trading.png
    - lib/images/portfolio.jpg
